"""
API endpoints that return statistics, e.g. cancer incidence/mortality,
or sociodemographic measures.
"""

from collections import defaultdict
from typing import Optional
from fastapi import Depends
from pydantic import BaseModel
from sqlalchemy import func
from sqlmodel import select
from sqlmodel.ext.asyncio.session import AsyncSession
from fastapi_pagination import Page
from fastapi_pagination.ext.sqlmodel import paginate

from tools.strings import slug_modelname_sans_type
from db import get_session

from settings import LIMIT_TO_STATE

from models import (
    STATS_MODELS,
    CANCER_MODELS,
    MEASURE_DESCRIPTIONS
)

from fastapi import APIRouter

router = APIRouter(prefix="/stats")


# ============================================================================
# === statistics routes
# ============================================================================

class FIPSMeasureResponse(BaseModel):
    min: Optional[float]
    max: Optional[float]
    values: dict[str,float]

# provides high-level information about the available categories and measures
# by iterating over the STATS_MODELS dict

class MeasuresMetaResponse(BaseModel):
    display_name: str

class CateogryMetaResponse(BaseModel):
    display_name: str
    measures: dict[str, MeasuresMetaResponse]

class StatsMetaResponse(BaseModel):
    display_name: str
    categories: dict[str, CateogryMetaResponse]

@router.get(f"/measures", response_model=dict[str, StatsMetaResponse])
async def get_measures(session: AsyncSession = Depends(get_session)):
    f"""
    Autogenerated method; gets all distinct values of 'measure' for all stats tables.
    """

    # stores measures by type (country vs. tract) and table
    all_measures = {}

    for type, models in STATS_MODELS.items():
        all_measures[type] = {
            "display_name": type.capitalize(),
            "categories": {}
        }

        for model in models:
            simple_model_name = slug_modelname_sans_type(model, type)

            if model in CANCER_MODELS:
                query = select(model.Site).distinct().order_by(model.Site)
            else:
                query = select(model.measure).distinct().order_by(model.measure)
            
            # if LIMIT_TO_STATE is not None:
            #     query = query.where(model.State == LIMIT_TO_STATE)

            result = await session.execute(query)

            all_measures[type]["categories"][simple_model_name] = {
                "display_name": model.Config.display_name or simple_model_name,
                "measures": {
                    x: {
                        "display_name": MEASURE_DESCRIPTIONS.get(simple_model_name, {}).get(x, x) or x,
                    }
                    for x in result.scalars().all()
                }
            }

    return all_measures


# generates a set of stats endpoints per model from the STATS_MODELS dict

for type, family in STATS_MODELS.items():
    for model in family:
        simple_model_name = slug_modelname_sans_type(model, type)

        # despite us iterating over 'model' in the loop, we need to use a closure to
        # capture the value of 'model' at the time of the loop iteration. in this
        # case, the closure is the "generate_routes" function below that closes
        # model as an argument.
        # otherwise the methods will use the most recent value of 'model', which
        # will always be the last model in the list.

        def generate_routes(model=model):
            @router.get(
                f"/{type}/{simple_model_name}/measures", 
                response_model=list[str],
                description=f"""
                Autogenerated method; gets all distinct values of 'measure' for the {model.__name__} table.
                """
            )
            async def get_dataset_measures(session: AsyncSession = Depends(get_session)):
                # check if model is a cancer model
                # if so, we need to use the "Site" column instead of "measure"
                if model in CANCER_MODELS:
                    query = select(model.Site).distinct().order_by(model.Site)
                else:
                    query = select(model.measure).distinct().order_by(model.measure)
                
                if LIMIT_TO_STATE is not None:
                    query = query.where(model.State == LIMIT_TO_STATE)

                result = await session.execute(query)
                objects = result.scalars().all()

                return objects

            @router.get(
                f"/{type}/{simple_model_name}",
                response_model=Page[model], 
                description=f"""
                Autogenerated method; gets all rows from the {model.__name__} table. Returns the results as a paginated list.
                """
            )
            async def get_dataset(
                measure: Optional[str] = None, session: AsyncSession = Depends(get_session)
            ):
                query = select(model)
                
                if LIMIT_TO_STATE is not None:
                    query = query.where(model.State == LIMIT_TO_STATE)

                if measure is not None:
                    query = query.where(model.measure == measure)

                result = await paginate(session, query)

                return result
            
            @router.get(
                f"/{type}/{simple_model_name}/fips-value",
                response_model=FIPSMeasureResponse,
                description=f"""
                Autogenerated method; gets pairings of FIPS (an ID that, in this case,
                specifies geographic regions) and the value of the given measure for that
                region.
                """
            )
            async def get_dataset_fips(
                measure: str, session: AsyncSession = Depends(get_session)
            ):
                print(f"Processing {model.__name__} for measure {measure}")

                if model not in CANCER_MODELS:
                    query = select((model.FIPS, model.value)).where(model.measure == measure)
                else:
                    query = select((model.FIPS, model.AAR.label("value"))).where(model.Site == measure)
                
                if LIMIT_TO_STATE is not None:
                    query = query.where(model.State == LIMIT_TO_STATE)

                # compute mins and maxes so we can build a color scale
                # # if it's a cancer endpint, we need to use the "Site" column instead of "measure", and "AAR" instead of "value
                if model not in CANCER_MODELS:
                    stats_query = select(func.min(model.value), func.max(model.value)).where(model.measure == measure)
                else:
                    stats_query = select(func.min(model.AAR), func.max(model.AAR)).where(model.Site == measure)
                
                stats_result = await session.execute(stats_query)
                stats = stats_result.all()[0]

                result = await session.execute(query)
                objects = result.all()
                return FIPSMeasureResponse(
                    min=stats[0],
                    max=stats[1],
                    values={x["FIPS"]: x["value"] for x in objects}
                )

        generate_routes()
