"""Added stats tables

Revision ID: 087ad506547e
Revises: 
Create Date: 2023-08-21 17:36:56.878719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '087ad506547e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('us_state',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abbreviation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_us_state_abbreviation'), 'us_state', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_us_state_name'), 'us_state', ['name'], unique=False)
    op.create_table('cancerincidencecounty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Site', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('AAR', sa.Float(), nullable=False),
    sa.Column('AAC', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cancerincidencecounty_County'), 'cancerincidencecounty', ['County'], unique=False)
    op.create_index(op.f('ix_cancerincidencecounty_FIPS'), 'cancerincidencecounty', ['FIPS'], unique=False)
    op.create_index(op.f('ix_cancerincidencecounty_Site'), 'cancerincidencecounty', ['Site'], unique=False)
    op.create_index(op.f('ix_cancerincidencecounty_State'), 'cancerincidencecounty', ['State'], unique=False)
    op.create_index(op.f('ix_cancerincidencecounty_Type'), 'cancerincidencecounty', ['Type'], unique=False)
    op.create_table('cancermortalitycounty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Site', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('AAR', sa.Float(), nullable=False),
    sa.Column('AAC', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cancermortalitycounty_County'), 'cancermortalitycounty', ['County'], unique=False)
    op.create_index(op.f('ix_cancermortalitycounty_FIPS'), 'cancermortalitycounty', ['FIPS'], unique=False)
    op.create_index(op.f('ix_cancermortalitycounty_Site'), 'cancermortalitycounty', ['Site'], unique=False)
    op.create_index(op.f('ix_cancermortalitycounty_State'), 'cancermortalitycounty', ['State'], unique=False)
    op.create_index(op.f('ix_cancermortalitycounty_Type'), 'cancermortalitycounty', ['Type'], unique=False)
    op.create_table('economycounty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economycounty_County'), 'economycounty', ['County'], unique=False)
    op.create_index(op.f('ix_economycounty_FIPS'), 'economycounty', ['FIPS'], unique=False)
    op.create_index(op.f('ix_economycounty_State'), 'economycounty', ['State'], unique=False)
    op.create_index(op.f('ix_economycounty_measure'), 'economycounty', ['measure'], unique=False)
    op.create_table('economytract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('Tract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economytract_County'), 'economytract', ['County'], unique=False)
    op.create_index(op.f('ix_economytract_FIPS'), 'economytract', ['FIPS'], unique=False)
    op.create_index(op.f('ix_economytract_State'), 'economytract', ['State'], unique=False)
    op.create_index(op.f('ix_economytract_Tract'), 'economytract', ['Tract'], unique=False)
    op.create_index(op.f('ix_economytract_measure'), 'economytract', ['measure'], unique=False)
    op.create_table('environmentcounty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmentcounty_County'), 'environmentcounty', ['County'], unique=False)
    op.create_index(op.f('ix_environmentcounty_FIPS'), 'environmentcounty', ['FIPS'], unique=False)
    op.create_index(op.f('ix_environmentcounty_State'), 'environmentcounty', ['State'], unique=False)
    op.create_index(op.f('ix_environmentcounty_measure'), 'environmentcounty', ['measure'], unique=False)
    op.create_table('environmenttract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('Tract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmenttract_County'), 'environmenttract', ['County'], unique=False)
    op.create_index(op.f('ix_environmenttract_FIPS'), 'environmenttract', ['FIPS'], unique=False)
    op.create_index(op.f('ix_environmenttract_State'), 'environmenttract', ['State'], unique=False)
    op.create_index(op.f('ix_environmenttract_Tract'), 'environmenttract', ['Tract'], unique=False)
    op.create_index(op.f('ix_environmenttract_measure'), 'environmenttract', ['measure'], unique=False)
    op.create_table('fooddeserttract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('Tract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fooddeserttract_County'), 'fooddeserttract', ['County'], unique=False)
    op.create_index(op.f('ix_fooddeserttract_FIPS'), 'fooddeserttract', ['FIPS'], unique=False)
    op.create_index(op.f('ix_fooddeserttract_State'), 'fooddeserttract', ['State'], unique=False)
    op.create_index(op.f('ix_fooddeserttract_Tract'), 'fooddeserttract', ['Tract'], unique=False)
    op.create_index(op.f('ix_fooddeserttract_measure'), 'fooddeserttract', ['measure'], unique=False)
    op.create_table('housingtranscounty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_housingtranscounty_County'), 'housingtranscounty', ['County'], unique=False)
    op.create_index(op.f('ix_housingtranscounty_FIPS'), 'housingtranscounty', ['FIPS'], unique=False)
    op.create_index(op.f('ix_housingtranscounty_State'), 'housingtranscounty', ['State'], unique=False)
    op.create_index(op.f('ix_housingtranscounty_measure'), 'housingtranscounty', ['measure'], unique=False)
    op.create_table('housingtranstract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('Tract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_housingtranstract_County'), 'housingtranstract', ['County'], unique=False)
    op.create_index(op.f('ix_housingtranstract_FIPS'), 'housingtranstract', ['FIPS'], unique=False)
    op.create_index(op.f('ix_housingtranstract_State'), 'housingtranstract', ['State'], unique=False)
    op.create_index(op.f('ix_housingtranstract_Tract'), 'housingtranstract', ['Tract'], unique=False)
    op.create_index(op.f('ix_housingtranstract_measure'), 'housingtranstract', ['measure'], unique=False)
    op.create_table('rfandscreeningcounty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfandscreeningcounty_County'), 'rfandscreeningcounty', ['County'], unique=False)
    op.create_index(op.f('ix_rfandscreeningcounty_FIPS'), 'rfandscreeningcounty', ['FIPS'], unique=False)
    op.create_index(op.f('ix_rfandscreeningcounty_State'), 'rfandscreeningcounty', ['State'], unique=False)
    op.create_index(op.f('ix_rfandscreeningcounty_measure'), 'rfandscreeningcounty', ['measure'], unique=False)
    op.create_table('rfandscreeningtract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('Tract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfandscreeningtract_County'), 'rfandscreeningtract', ['County'], unique=False)
    op.create_index(op.f('ix_rfandscreeningtract_FIPS'), 'rfandscreeningtract', ['FIPS'], unique=False)
    op.create_index(op.f('ix_rfandscreeningtract_State'), 'rfandscreeningtract', ['State'], unique=False)
    op.create_index(op.f('ix_rfandscreeningtract_Tract'), 'rfandscreeningtract', ['Tract'], unique=False)
    op.create_index(op.f('ix_rfandscreeningtract_measure'), 'rfandscreeningtract', ['measure'], unique=False)
    op.create_table('sociodemographicscounty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sociodemographicscounty_County'), 'sociodemographicscounty', ['County'], unique=False)
    op.create_index(op.f('ix_sociodemographicscounty_FIPS'), 'sociodemographicscounty', ['FIPS'], unique=False)
    op.create_index(op.f('ix_sociodemographicscounty_State'), 'sociodemographicscounty', ['State'], unique=False)
    op.create_index(op.f('ix_sociodemographicscounty_measure'), 'sociodemographicscounty', ['measure'], unique=False)
    op.create_table('sociodemographicstract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('Tract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sociodemographicstract_County'), 'sociodemographicstract', ['County'], unique=False)
    op.create_index(op.f('ix_sociodemographicstract_FIPS'), 'sociodemographicstract', ['FIPS'], unique=False)
    op.create_index(op.f('ix_sociodemographicstract_State'), 'sociodemographicstract', ['State'], unique=False)
    op.create_index(op.f('ix_sociodemographicstract_Tract'), 'sociodemographicstract', ['Tract'], unique=False)
    op.create_index(op.f('ix_sociodemographicstract_measure'), 'sociodemographicstract', ['measure'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sociodemographicstract_measure'), table_name='sociodemographicstract')
    op.drop_index(op.f('ix_sociodemographicstract_Tract'), table_name='sociodemographicstract')
    op.drop_index(op.f('ix_sociodemographicstract_State'), table_name='sociodemographicstract')
    op.drop_index(op.f('ix_sociodemographicstract_FIPS'), table_name='sociodemographicstract')
    op.drop_index(op.f('ix_sociodemographicstract_County'), table_name='sociodemographicstract')
    op.drop_table('sociodemographicstract')
    op.drop_index(op.f('ix_sociodemographicscounty_measure'), table_name='sociodemographicscounty')
    op.drop_index(op.f('ix_sociodemographicscounty_State'), table_name='sociodemographicscounty')
    op.drop_index(op.f('ix_sociodemographicscounty_FIPS'), table_name='sociodemographicscounty')
    op.drop_index(op.f('ix_sociodemographicscounty_County'), table_name='sociodemographicscounty')
    op.drop_table('sociodemographicscounty')
    op.drop_index(op.f('ix_rfandscreeningtract_measure'), table_name='rfandscreeningtract')
    op.drop_index(op.f('ix_rfandscreeningtract_Tract'), table_name='rfandscreeningtract')
    op.drop_index(op.f('ix_rfandscreeningtract_State'), table_name='rfandscreeningtract')
    op.drop_index(op.f('ix_rfandscreeningtract_FIPS'), table_name='rfandscreeningtract')
    op.drop_index(op.f('ix_rfandscreeningtract_County'), table_name='rfandscreeningtract')
    op.drop_table('rfandscreeningtract')
    op.drop_index(op.f('ix_rfandscreeningcounty_measure'), table_name='rfandscreeningcounty')
    op.drop_index(op.f('ix_rfandscreeningcounty_State'), table_name='rfandscreeningcounty')
    op.drop_index(op.f('ix_rfandscreeningcounty_FIPS'), table_name='rfandscreeningcounty')
    op.drop_index(op.f('ix_rfandscreeningcounty_County'), table_name='rfandscreeningcounty')
    op.drop_table('rfandscreeningcounty')
    op.drop_index(op.f('ix_housingtranstract_measure'), table_name='housingtranstract')
    op.drop_index(op.f('ix_housingtranstract_Tract'), table_name='housingtranstract')
    op.drop_index(op.f('ix_housingtranstract_State'), table_name='housingtranstract')
    op.drop_index(op.f('ix_housingtranstract_FIPS'), table_name='housingtranstract')
    op.drop_index(op.f('ix_housingtranstract_County'), table_name='housingtranstract')
    op.drop_table('housingtranstract')
    op.drop_index(op.f('ix_housingtranscounty_measure'), table_name='housingtranscounty')
    op.drop_index(op.f('ix_housingtranscounty_State'), table_name='housingtranscounty')
    op.drop_index(op.f('ix_housingtranscounty_FIPS'), table_name='housingtranscounty')
    op.drop_index(op.f('ix_housingtranscounty_County'), table_name='housingtranscounty')
    op.drop_table('housingtranscounty')
    op.drop_index(op.f('ix_fooddeserttract_measure'), table_name='fooddeserttract')
    op.drop_index(op.f('ix_fooddeserttract_Tract'), table_name='fooddeserttract')
    op.drop_index(op.f('ix_fooddeserttract_State'), table_name='fooddeserttract')
    op.drop_index(op.f('ix_fooddeserttract_FIPS'), table_name='fooddeserttract')
    op.drop_index(op.f('ix_fooddeserttract_County'), table_name='fooddeserttract')
    op.drop_table('fooddeserttract')
    op.drop_index(op.f('ix_environmenttract_measure'), table_name='environmenttract')
    op.drop_index(op.f('ix_environmenttract_Tract'), table_name='environmenttract')
    op.drop_index(op.f('ix_environmenttract_State'), table_name='environmenttract')
    op.drop_index(op.f('ix_environmenttract_FIPS'), table_name='environmenttract')
    op.drop_index(op.f('ix_environmenttract_County'), table_name='environmenttract')
    op.drop_table('environmenttract')
    op.drop_index(op.f('ix_environmentcounty_measure'), table_name='environmentcounty')
    op.drop_index(op.f('ix_environmentcounty_State'), table_name='environmentcounty')
    op.drop_index(op.f('ix_environmentcounty_FIPS'), table_name='environmentcounty')
    op.drop_index(op.f('ix_environmentcounty_County'), table_name='environmentcounty')
    op.drop_table('environmentcounty')
    op.drop_index(op.f('ix_economytract_measure'), table_name='economytract')
    op.drop_index(op.f('ix_economytract_Tract'), table_name='economytract')
    op.drop_index(op.f('ix_economytract_State'), table_name='economytract')
    op.drop_index(op.f('ix_economytract_FIPS'), table_name='economytract')
    op.drop_index(op.f('ix_economytract_County'), table_name='economytract')
    op.drop_table('economytract')
    op.drop_index(op.f('ix_economycounty_measure'), table_name='economycounty')
    op.drop_index(op.f('ix_economycounty_State'), table_name='economycounty')
    op.drop_index(op.f('ix_economycounty_FIPS'), table_name='economycounty')
    op.drop_index(op.f('ix_economycounty_County'), table_name='economycounty')
    op.drop_table('economycounty')
    op.drop_index(op.f('ix_cancermortalitycounty_Type'), table_name='cancermortalitycounty')
    op.drop_index(op.f('ix_cancermortalitycounty_State'), table_name='cancermortalitycounty')
    op.drop_index(op.f('ix_cancermortalitycounty_Site'), table_name='cancermortalitycounty')
    op.drop_index(op.f('ix_cancermortalitycounty_FIPS'), table_name='cancermortalitycounty')
    op.drop_index(op.f('ix_cancermortalitycounty_County'), table_name='cancermortalitycounty')
    op.drop_table('cancermortalitycounty')
    op.drop_index(op.f('ix_cancerincidencecounty_Type'), table_name='cancerincidencecounty')
    op.drop_index(op.f('ix_cancerincidencecounty_State'), table_name='cancerincidencecounty')
    op.drop_index(op.f('ix_cancerincidencecounty_Site'), table_name='cancerincidencecounty')
    op.drop_index(op.f('ix_cancerincidencecounty_FIPS'), table_name='cancerincidencecounty')
    op.drop_index(op.f('ix_cancerincidencecounty_County'), table_name='cancerincidencecounty')
    op.drop_table('cancerincidencecounty')
    op.drop_index(op.f('ix_us_state_name'), table_name='us_state')
    op.drop_index(op.f('ix_us_state_abbreviation'), table_name='us_state')
    op.drop_table('us_state')
    # ### end Alembic commands ###
