"""Added FIPS column to VapingHealthRegion

Revision ID: 1310b8432410
Revises: b1ed4c973c11
Create Date: 2024-12-05 18:00:49.785841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1310b8432410'
down_revision: Union[str, None] = 'b1ed4c973c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('healthregion', 'objectid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('healthregion', 'FIPS',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('healthregion', 'hs_region',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('healthregion', 'counties',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('healthregion_wkb_geometry_geom_idx', table_name='healthregion')
    op.create_index(op.f('ix_healthregion_FIPS'), 'healthregion', ['FIPS'], unique=False)
    op.create_index(op.f('ix_healthregion_counties'), 'healthregion', ['counties'], unique=False)
    op.create_index(op.f('ix_healthregion_hs_region'), 'healthregion', ['hs_region'], unique=False)
    op.create_index(op.f('ix_healthregion_objectid'), 'healthregion', ['objectid'], unique=True)
    op.drop_column('healthregion', 'state')
    op.add_column('vapinghealthregion', sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_vapinghealthregion_FIPS'), 'vapinghealthregion', ['FIPS'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vapinghealthregion_FIPS'), table_name='vapinghealthregion')
    op.drop_column('vapinghealthregion', 'FIPS')
    op.add_column('healthregion', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_healthregion_objectid'), table_name='healthregion')
    op.drop_index(op.f('ix_healthregion_hs_region'), table_name='healthregion')
    op.drop_index(op.f('ix_healthregion_counties'), table_name='healthregion')
    op.drop_index(op.f('ix_healthregion_FIPS'), table_name='healthregion')
    op.create_index('healthregion_wkb_geometry_geom_idx', 'healthregion', ['wkb_geometry'], unique=False)
    op.alter_column('healthregion', 'counties',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthregion', 'hs_region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthregion', 'FIPS',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthregion', 'objectid',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
