"""added locations

Revision ID: 2f3ac89e6ffe
Revises: 40972f34ab5b
Create Date: 2024-07-19 17:05:30.730679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f3ac89e6ffe'
down_revision: Union[str, None] = '40972f34ab5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locationcategory',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locationcategory_id'), 'locationcategory', ['id'], unique=False)
    op.create_index(op.f('ix_locationcategory_name'), 'locationcategory', ['name'], unique=False)
    op.create_table('location',
    sa.Column('geometry_json', sa.JSON(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['locationcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_category_id'), 'location', ['category_id'], unique=False)
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_index(op.f('ix_location_category_id'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_locationcategory_name'), table_name='locationcategory')
    op.drop_index(op.f('ix_locationcategory_id'), table_name='locationcategory')
    op.drop_table('locationcategory')
    # ### end Alembic commands ###
