"""added state-level table for youth vaping data

Revision ID: 4c47c1001dc4
Revises: 5c847826cf93
Create Date: 2025-01-23 17:55:25.147820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c47c1001dc4'
down_revision: Union[str, None] = '5c847826cf93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stateyouthvapingstats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measure_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_avg', sa.Float(), nullable=False),
    sa.Column('us_avg', sa.Float(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stateyouthvapingstats_measure'), 'stateyouthvapingstats', ['measure'], unique=False)
    op.create_index(op.f('ix_stateyouthvapingstats_measure_category'), 'stateyouthvapingstats', ['measure_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stateyouthvapingstats_measure_category'), table_name='stateyouthvapingstats')
    op.drop_index(op.f('ix_stateyouthvapingstats_measure'), table_name='stateyouthvapingstats')
    op.drop_table('stateyouthvapingstats')
    # ### end Alembic commands ###
