"""Adds 'trend' field to SCP models

Revision ID: 54f089a75019
Revises: adb04bc6d4dd
Create Date: 2024-04-25 23:34:23.529188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54f089a75019'
down_revision: Union[str, None] = 'adb04bc6d4dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scpdeathscounty', sa.Column('trend', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('scpincidencecounty', sa.Column('trend', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scpincidencecounty', 'trend')
    op.drop_column('scpdeathscounty', 'trend')
    # ### end Alembic commands ###
