"""Added RE, Sex fields to cancer models

Revision ID: 56c1a3bb17d7
Revises: aefecd73a242
Create Date: 2024-02-22 17:37:00.482750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '56c1a3bb17d7'
down_revision: Union[str, None] = 'aefecd73a242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cancerincidencecounty', sa.Column('RE', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('cancerincidencecounty', sa.Column('Sex', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_cancerincidencecounty_RE'), 'cancerincidencecounty', ['RE'], unique=False)
    op.create_index(op.f('ix_cancerincidencecounty_Sex'), 'cancerincidencecounty', ['Sex'], unique=False)
    op.add_column('cancermortalitycounty', sa.Column('RE', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('cancermortalitycounty', sa.Column('Sex', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_cancermortalitycounty_RE'), 'cancermortalitycounty', ['RE'], unique=False)
    op.create_index(op.f('ix_cancermortalitycounty_Sex'), 'cancermortalitycounty', ['Sex'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cancermortalitycounty_Sex'), table_name='cancermortalitycounty')
    op.drop_index(op.f('ix_cancermortalitycounty_RE'), table_name='cancermortalitycounty')
    op.drop_column('cancermortalitycounty', 'Sex')
    op.drop_column('cancermortalitycounty', 'RE')
    op.drop_index(op.f('ix_cancerincidencecounty_Sex'), table_name='cancerincidencecounty')
    op.drop_index(op.f('ix_cancerincidencecounty_RE'), table_name='cancerincidencecounty')
    op.drop_column('cancerincidencecounty', 'Sex')
    op.drop_column('cancerincidencecounty', 'RE')
    # ### end Alembic commands ###
