"""general factor field for vaping data

Revision ID: 5c847826cf93
Revises: b1ed4c973c11
Create Date: 2025-01-23 17:41:51.812794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c847826cf93'
down_revision: Union[str, None] = 'b1ed4c973c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('healthregion', 'objectid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('healthregion', 'hs_region',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('healthregion', 'counties',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('healthregion_wkb_geometry_geom_idx', table_name='healthregion')
    op.create_index(op.f('ix_healthregion_counties'), 'healthregion', ['counties'], unique=False)
    op.create_index(op.f('ix_healthregion_hs_region'), 'healthregion', ['hs_region'], unique=False)
    op.create_index(op.f('ix_healthregion_objectid'), 'healthregion', ['objectid'], unique=True)
    op.drop_column('healthregion', 'state')
    op.add_column('vapinghealthregion', sa.Column('factor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('ix_vapinghealthregion_age', table_name='vapinghealthregion')
    op.drop_index('ix_vapinghealthregion_race', table_name='vapinghealthregion')
    op.drop_index('ix_vapinghealthregion_sex', table_name='vapinghealthregion')
    op.create_index(op.f('ix_vapinghealthregion_factor'), 'vapinghealthregion', ['factor'], unique=False)
    op.drop_column('vapinghealthregion', 'age')
    op.drop_column('vapinghealthregion', 'race')
    op.drop_column('vapinghealthregion', 'sex')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vapinghealthregion', sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vapinghealthregion', sa.Column('race', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vapinghealthregion', sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vapinghealthregion_factor'), table_name='vapinghealthregion')
    op.create_index('ix_vapinghealthregion_sex', 'vapinghealthregion', ['sex'], unique=False)
    op.create_index('ix_vapinghealthregion_race', 'vapinghealthregion', ['race'], unique=False)
    op.create_index('ix_vapinghealthregion_age', 'vapinghealthregion', ['age'], unique=False)
    op.drop_column('vapinghealthregion', 'factor')
    op.add_column('healthregion', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_healthregion_objectid'), table_name='healthregion')
    op.drop_index(op.f('ix_healthregion_hs_region'), table_name='healthregion')
    op.drop_index(op.f('ix_healthregion_counties'), table_name='healthregion')
    op.create_index('healthregion_wkb_geometry_geom_idx', 'healthregion', ['wkb_geometry'], unique=False)
    op.alter_column('healthregion', 'counties',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthregion', 'hs_region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthregion', 'objectid',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
