"""Refactors SCP models to be based on CancerStatsModels

Revision ID: 614c25756e6b
Revises: 238ba426fade
Create Date: 2024-04-26 17:18:57.456398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '614c25756e6b'
down_revision: Union[str, None] = '238ba426fade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scpdeathscounty', sa.Column('Site', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('scpdeathscounty', sa.Column('AAR', sa.Float(), nullable=False))
    op.add_column('scpdeathscounty', sa.Column('AAC', sa.Float(), nullable=False))
    op.drop_index('ix_scpdeathscounty_measure', table_name='scpdeathscounty')
    op.create_index(op.f('ix_scpdeathscounty_Site'), 'scpdeathscounty', ['Site'], unique=False)
    op.drop_column('scpdeathscounty', 'measure')
    op.drop_column('scpdeathscounty', 'value')
    op.add_column('scpincidencecounty', sa.Column('Site', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('scpincidencecounty', sa.Column('AAR', sa.Float(), nullable=False))
    op.add_column('scpincidencecounty', sa.Column('AAC', sa.Float(), nullable=False))
    op.drop_index('ix_scpincidencecounty_measure', table_name='scpincidencecounty')
    op.create_index(op.f('ix_scpincidencecounty_Site'), 'scpincidencecounty', ['Site'], unique=False)
    op.drop_column('scpincidencecounty', 'measure')
    op.drop_column('scpincidencecounty', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scpincidencecounty', sa.Column('value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('scpincidencecounty', sa.Column('measure', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_scpincidencecounty_Site'), table_name='scpincidencecounty')
    op.create_index('ix_scpincidencecounty_measure', 'scpincidencecounty', ['measure'], unique=False)
    op.drop_column('scpincidencecounty', 'AAC')
    op.drop_column('scpincidencecounty', 'AAR')
    op.drop_column('scpincidencecounty', 'Site')
    op.add_column('scpdeathscounty', sa.Column('value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('scpdeathscounty', sa.Column('measure', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_scpdeathscounty_Site'), table_name='scpdeathscounty')
    op.create_index('ix_scpdeathscounty_measure', 'scpdeathscounty', ['measure'], unique=False)
    op.drop_column('scpdeathscounty', 'AAC')
    op.drop_column('scpdeathscounty', 'AAR')
    op.drop_column('scpdeathscounty', 'Site')
    # ### end Alembic commands ###
