"""added CiF disparities tables

Revision ID: 63a524442a63
Revises: 56c1a3bb17d7
Create Date: 2024-03-04 23:42:19.656250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '63a524442a63'
down_revision: Union[str, None] = '56c1a3bb17d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disparitiescounty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disparitiescounty_County'), 'disparitiescounty', ['County'], unique=False)
    op.create_index(op.f('ix_disparitiescounty_FIPS'), 'disparitiescounty', ['FIPS'], unique=False)
    op.create_index(op.f('ix_disparitiescounty_State'), 'disparitiescounty', ['State'], unique=False)
    op.create_index(op.f('ix_disparitiescounty_measure'), 'disparitiescounty', ['measure'], unique=False)
    op.create_table('disparitiestract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('Tract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disparitiestract_County'), 'disparitiestract', ['County'], unique=False)
    op.create_index(op.f('ix_disparitiestract_FIPS'), 'disparitiestract', ['FIPS'], unique=False)
    op.create_index(op.f('ix_disparitiestract_State'), 'disparitiestract', ['State'], unique=False)
    op.create_index(op.f('ix_disparitiestract_Tract'), 'disparitiestract', ['Tract'], unique=False)
    op.create_index(op.f('ix_disparitiestract_measure'), 'disparitiestract', ['measure'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disparitiestract_measure'), table_name='disparitiestract')
    op.drop_index(op.f('ix_disparitiestract_Tract'), table_name='disparitiestract')
    op.drop_index(op.f('ix_disparitiestract_State'), table_name='disparitiestract')
    op.drop_index(op.f('ix_disparitiestract_FIPS'), table_name='disparitiestract')
    op.drop_index(op.f('ix_disparitiestract_County'), table_name='disparitiestract')
    op.drop_table('disparitiestract')
    op.drop_index(op.f('ix_disparitiescounty_measure'), table_name='disparitiescounty')
    op.drop_index(op.f('ix_disparitiescounty_State'), table_name='disparitiescounty')
    op.drop_index(op.f('ix_disparitiescounty_FIPS'), table_name='disparitiescounty')
    op.drop_index(op.f('ix_disparitiescounty_County'), table_name='disparitiescounty')
    op.drop_table('disparitiescounty')
    # ### end Alembic commands ###
