"""Adds UV exposure model

Revision ID: 7214c6efee37
Revises: d3447339ba7b
Create Date: 2025-09-16 11:39:59.611481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7214c6efee37'
down_revision: Union[str, None] = 'd3447339ba7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uvexposurecounty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uvexposurecounty_County'), 'uvexposurecounty', ['County'], unique=False)
    op.create_index(op.f('ix_uvexposurecounty_FIPS'), 'uvexposurecounty', ['FIPS'], unique=False)
    op.create_index(op.f('ix_uvexposurecounty_State'), 'uvexposurecounty', ['State'], unique=False)
    op.create_index(op.f('ix_uvexposurecounty_measure'), 'uvexposurecounty', ['measure'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uvexposurecounty_measure'), table_name='uvexposurecounty')
    op.drop_index(op.f('ix_uvexposurecounty_State'), table_name='uvexposurecounty')
    op.drop_index(op.f('ix_uvexposurecounty_FIPS'), table_name='uvexposurecounty')
    op.drop_index(op.f('ix_uvexposurecounty_County'), table_name='uvexposurecounty')
    op.drop_table('uvexposurecounty')
    # ### end Alembic commands ###
