"""Adds SCP models

Revision ID: adb04bc6d4dd
Revises: 491f02babf92
Create Date: 2024-04-25 20:50:32.943845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'adb04bc6d4dd'
down_revision: Union[str, None] = '491f02babf92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scpdeathscounty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('race', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scpdeathscounty_County'), 'scpdeathscounty', ['County'], unique=False)
    op.create_index(op.f('ix_scpdeathscounty_FIPS'), 'scpdeathscounty', ['FIPS'], unique=False)
    op.create_index(op.f('ix_scpdeathscounty_State'), 'scpdeathscounty', ['State'], unique=False)
    op.create_index(op.f('ix_scpdeathscounty_age'), 'scpdeathscounty', ['age'], unique=False)
    op.create_index(op.f('ix_scpdeathscounty_measure'), 'scpdeathscounty', ['measure'], unique=False)
    op.create_index(op.f('ix_scpdeathscounty_race'), 'scpdeathscounty', ['race'], unique=False)
    op.create_index(op.f('ix_scpdeathscounty_sex'), 'scpdeathscounty', ['sex'], unique=False)
    op.create_index(op.f('ix_scpdeathscounty_stage'), 'scpdeathscounty', ['stage'], unique=False)
    op.create_table('scpincidencecounty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('race', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scpincidencecounty_County'), 'scpincidencecounty', ['County'], unique=False)
    op.create_index(op.f('ix_scpincidencecounty_FIPS'), 'scpincidencecounty', ['FIPS'], unique=False)
    op.create_index(op.f('ix_scpincidencecounty_State'), 'scpincidencecounty', ['State'], unique=False)
    op.create_index(op.f('ix_scpincidencecounty_age'), 'scpincidencecounty', ['age'], unique=False)
    op.create_index(op.f('ix_scpincidencecounty_measure'), 'scpincidencecounty', ['measure'], unique=False)
    op.create_index(op.f('ix_scpincidencecounty_race'), 'scpincidencecounty', ['race'], unique=False)
    op.create_index(op.f('ix_scpincidencecounty_sex'), 'scpincidencecounty', ['sex'], unique=False)
    op.create_index(op.f('ix_scpincidencecounty_stage'), 'scpincidencecounty', ['stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scpincidencecounty_stage'), table_name='scpincidencecounty')
    op.drop_index(op.f('ix_scpincidencecounty_sex'), table_name='scpincidencecounty')
    op.drop_index(op.f('ix_scpincidencecounty_race'), table_name='scpincidencecounty')
    op.drop_index(op.f('ix_scpincidencecounty_measure'), table_name='scpincidencecounty')
    op.drop_index(op.f('ix_scpincidencecounty_age'), table_name='scpincidencecounty')
    op.drop_index(op.f('ix_scpincidencecounty_State'), table_name='scpincidencecounty')
    op.drop_index(op.f('ix_scpincidencecounty_FIPS'), table_name='scpincidencecounty')
    op.drop_index(op.f('ix_scpincidencecounty_County'), table_name='scpincidencecounty')
    op.drop_table('scpincidencecounty')
    op.drop_index(op.f('ix_scpdeathscounty_stage'), table_name='scpdeathscounty')
    op.drop_index(op.f('ix_scpdeathscounty_sex'), table_name='scpdeathscounty')
    op.drop_index(op.f('ix_scpdeathscounty_race'), table_name='scpdeathscounty')
    op.drop_index(op.f('ix_scpdeathscounty_measure'), table_name='scpdeathscounty')
    op.drop_index(op.f('ix_scpdeathscounty_age'), table_name='scpdeathscounty')
    op.drop_index(op.f('ix_scpdeathscounty_State'), table_name='scpdeathscounty')
    op.drop_index(op.f('ix_scpdeathscounty_FIPS'), table_name='scpdeathscounty')
    op.drop_index(op.f('ix_scpdeathscounty_County'), table_name='scpdeathscounty')
    op.drop_table('scpdeathscounty')
    # ### end Alembic commands ###
