"""Added Youth Vaping tables, health regions

Revision ID: b1ed4c973c11
Revises: d3447339ba7b
Create Date: 2024-12-05 16:57:38.249919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b1ed4c973c11'
down_revision: Union[str, None] = 'd3447339ba7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vapinghealthregion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hs_region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('race', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vapinghealthregion_State'), 'vapinghealthregion', ['State'], unique=False)
    op.create_index(op.f('ix_vapinghealthregion_age'), 'vapinghealthregion', ['age'], unique=False)
    op.create_index(op.f('ix_vapinghealthregion_hs_region'), 'vapinghealthregion', ['hs_region'], unique=False)
    op.create_index(op.f('ix_vapinghealthregion_measure'), 'vapinghealthregion', ['measure'], unique=False)
    op.create_index(op.f('ix_vapinghealthregion_race'), 'vapinghealthregion', ['race'], unique=False)
    op.create_index(op.f('ix_vapinghealthregion_sex'), 'vapinghealthregion', ['sex'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vapinghealthregion_sex'), table_name='vapinghealthregion')
    op.drop_index(op.f('ix_vapinghealthregion_race'), table_name='vapinghealthregion')
    op.drop_index(op.f('ix_vapinghealthregion_measure'), table_name='vapinghealthregion')
    op.drop_index(op.f('ix_vapinghealthregion_hs_region'), table_name='vapinghealthregion')
    op.drop_index(op.f('ix_vapinghealthregion_age'), table_name='vapinghealthregion')
    op.drop_index(op.f('ix_vapinghealthregion_State'), table_name='vapinghealthregion')
    op.drop_table('vapinghealthregion')
    # ### end Alembic commands ###
