"""added HPV model

Revision ID: bf61b2255ed0
Revises: 40972f34ab5b
Create Date: 2024-07-23 20:07:32.078843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf61b2255ed0'
down_revision: Union[str, None] = '40972f34ab5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hpvcounty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hpvcounty_County'), 'hpvcounty', ['County'], unique=False)
    op.create_index(op.f('ix_hpvcounty_FIPS'), 'hpvcounty', ['FIPS'], unique=False)
    op.create_index(op.f('ix_hpvcounty_State'), 'hpvcounty', ['State'], unique=False)
    op.create_index(op.f('ix_hpvcounty_measure'), 'hpvcounty', ['measure'], unique=False)
    op.create_index(op.f('ix_hpvcounty_sex'), 'hpvcounty', ['sex'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hpvcounty_sex'), table_name='hpvcounty')
    op.drop_index(op.f('ix_hpvcounty_measure'), table_name='hpvcounty')
    op.drop_index(op.f('ix_hpvcounty_State'), table_name='hpvcounty')
    op.drop_index(op.f('ix_hpvcounty_FIPS'), table_name='hpvcounty')
    op.drop_index(op.f('ix_hpvcounty_County'), table_name='hpvcounty')
    op.drop_table('hpvcounty')
    # ### end Alembic commands ###
