"""added name to locations, made names unique

Revision ID: cb9412070fed
Revises: 2f3ac89e6ffe
Create Date: 2024-07-19 18:00:02.407484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb9412070fed'
down_revision: Union[str, None] = '2f3ac89e6ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_location_name'), 'location', ['name'], unique=True)
    op.drop_index('ix_locationcategory_name', table_name='locationcategory')
    op.create_index(op.f('ix_locationcategory_name'), 'locationcategory', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locationcategory_name'), table_name='locationcategory')
    op.create_index('ix_locationcategory_name', 'locationcategory', ['name'], unique=False)
    op.drop_index(op.f('ix_location_name'), table_name='location')
    op.drop_column('location', 'name')
    # ### end Alembic commands ###
