"""add state stats

Revision ID: d3447339ba7b
Revises: c09b3a8d7483
Create Date: 2024-09-23 17:07:19.773420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3447339ba7b'
down_revision: Union[str, None] = 'c09b3a8d7483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statecancerincidencestats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_avg', sa.Float(), nullable=False),
    sa.Column('us_avg', sa.Float(), nullable=True),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('race', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statecancerincidencestats_age'), 'statecancerincidencestats', ['age'], unique=False)
    op.create_index(op.f('ix_statecancerincidencestats_race'), 'statecancerincidencestats', ['race'], unique=False)
    op.create_index(op.f('ix_statecancerincidencestats_sex'), 'statecancerincidencestats', ['sex'], unique=False)
    op.create_index(op.f('ix_statecancerincidencestats_site'), 'statecancerincidencestats', ['site'], unique=False)
    op.create_index(op.f('ix_statecancerincidencestats_stage'), 'statecancerincidencestats', ['stage'], unique=False)
    op.create_table('statecancermortalitystats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_avg', sa.Float(), nullable=False),
    sa.Column('us_avg', sa.Float(), nullable=True),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('race', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statecancermortalitystats_age'), 'statecancermortalitystats', ['age'], unique=False)
    op.create_index(op.f('ix_statecancermortalitystats_race'), 'statecancermortalitystats', ['race'], unique=False)
    op.create_index(op.f('ix_statecancermortalitystats_sex'), 'statecancermortalitystats', ['sex'], unique=False)
    op.create_index(op.f('ix_statecancermortalitystats_site'), 'statecancermortalitystats', ['site'], unique=False)
    op.create_index(op.f('ix_statecancermortalitystats_stage'), 'statecancermortalitystats', ['stage'], unique=False)
    op.create_table('statesociodemographicstats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measure_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_avg', sa.Float(), nullable=False),
    sa.Column('us_avg', sa.Float(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statesociodemographicstats_measure'), 'statesociodemographicstats', ['measure'], unique=False)
    op.create_index(op.f('ix_statesociodemographicstats_measure_category'), 'statesociodemographicstats', ['measure_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statesociodemographicstats_measure_category'), table_name='statesociodemographicstats')
    op.drop_index(op.f('ix_statesociodemographicstats_measure'), table_name='statesociodemographicstats')
    op.drop_table('statesociodemographicstats')
    op.drop_index(op.f('ix_statecancermortalitystats_stage'), table_name='statecancermortalitystats')
    op.drop_index(op.f('ix_statecancermortalitystats_site'), table_name='statecancermortalitystats')
    op.drop_index(op.f('ix_statecancermortalitystats_sex'), table_name='statecancermortalitystats')
    op.drop_index(op.f('ix_statecancermortalitystats_race'), table_name='statecancermortalitystats')
    op.drop_index(op.f('ix_statecancermortalitystats_age'), table_name='statecancermortalitystats')
    op.drop_table('statecancermortalitystats')
    op.drop_index(op.f('ix_statecancerincidencestats_stage'), table_name='statecancerincidencestats')
    op.drop_index(op.f('ix_statecancerincidencestats_site'), table_name='statecancerincidencestats')
    op.drop_index(op.f('ix_statecancerincidencestats_sex'), table_name='statecancerincidencestats')
    op.drop_index(op.f('ix_statecancerincidencestats_race'), table_name='statecancerincidencestats')
    op.drop_index(op.f('ix_statecancerincidencestats_age'), table_name='statecancerincidencestats')
    op.drop_table('statecancerincidencestats')
    # ### end Alembic commands ###
