"""Added UCCC responders model

Revision ID: ef10763dbf40
Revises: 8a40c04c107c
Create Date: 2026-01-20 13:42:27.965241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ef10763dbf40'
down_revision: Union[str, None] = '8a40c04c107c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ucccresponderscounty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('County', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('urbanicity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['State'], ['us_state.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ucccresponderscounty_County'), 'ucccresponderscounty', ['County'], unique=False)
    op.create_index(op.f('ix_ucccresponderscounty_FIPS'), 'ucccresponderscounty', ['FIPS'], unique=False)
    op.create_index(op.f('ix_ucccresponderscounty_State'), 'ucccresponderscounty', ['State'], unique=False)
    op.create_index(op.f('ix_ucccresponderscounty_measure'), 'ucccresponderscounty', ['measure'], unique=False)
    op.create_index(op.f('ix_ucccresponderscounty_urbanicity'), 'ucccresponderscounty', ['urbanicity'], unique=False)
    op.alter_column('healthregion', 'objectid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('healthregion', 'hs_region',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('healthregion', 'counties',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('healthregion_wkb_geometry_geom_idx', table_name='healthregion')
    op.create_index(op.f('ix_healthregion_counties'), 'healthregion', ['counties'], unique=False)
    op.create_index(op.f('ix_healthregion_hs_region'), 'healthregion', ['hs_region'], unique=False)
    op.create_index(op.f('ix_healthregion_objectid'), 'healthregion', ['objectid'], unique=True)
    op.drop_column('healthregion', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('healthregion', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_healthregion_objectid'), table_name='healthregion')
    op.drop_index(op.f('ix_healthregion_hs_region'), table_name='healthregion')
    op.drop_index(op.f('ix_healthregion_counties'), table_name='healthregion')
    op.create_index('healthregion_wkb_geometry_geom_idx', 'healthregion', ['wkb_geometry'], unique=False)
    op.alter_column('healthregion', 'counties',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthregion', 'hs_region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('healthregion', 'objectid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_ucccresponderscounty_urbanicity'), table_name='ucccresponderscounty')
    op.drop_index(op.f('ix_ucccresponderscounty_measure'), table_name='ucccresponderscounty')
    op.drop_index(op.f('ix_ucccresponderscounty_State'), table_name='ucccresponderscounty')
    op.drop_index(op.f('ix_ucccresponderscounty_FIPS'), table_name='ucccresponderscounty')
    op.drop_index(op.f('ix_ucccresponderscounty_County'), table_name='ucccresponderscounty')
    op.drop_table('ucccresponderscounty')
    # ### end Alembic commands ###
