name: Create Monthly ECCO Release

# run both every month on the 3rd and also
# via the workflow_dispatch event
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 3 * *'

jobs:
  create_release:
    runs-on: 'ubuntu-latest'

    # the pipeline needs to do the following:
    # 1. check out the repo
    # 2. set up docker with docker compose
    # 3. set the following env vars:
    #    - NONINTERACTIVE=1
    #    - FORCE_ACQUIRE_RELEASE=1
    #    - FORCE_DELETE_DB_BEFORE_IMPORT=1
    # 3. run the script ./data/pipeline/produce_release.sh
    # 4. copy the latest dump from /db-exports/ to /releases/
    # 5. create a new release on the repo with the dump as an asset

    steps:
    - uses: 'actions/checkout@v4'

    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1

    - name: Set up env vars
      run: |-
          echo "NONINTERACTIVE=1" >> $GITHUB_ENV
          echo "FORCE_ACQUIRE_RELEASE=1" >> $GITHUB_ENV
          echo "FORCE_DELETE_DB_BEFORE_IMPORT=1" >> $GITHUB_ENV

    - name: Produce release
      run: |-
          cd ./data/pipeline
          ./produce_release.sh

    - name: Copy dump to releases
      run: |-
          # list the /db-exports folder and sort
          # by date, taking the most recent file
          cp $( ls -t /db-exports/ | head -n 1 ) /tmp/release/

    - name: Create release
      run: |-
          gh release create $( date +%Y-%m-%d ) /tmp/release/
