name: Create Monthly ECCO Release

# this workflow is a stub, to allow us to run the actual
# workflow on the issue-74-automate-ingest-pipeline branch
on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
