name: Deploy ECCO to VM
on:
  push:
    branches:
      - main

jobs:
  deploy_prod:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v4'

      - id: 'compute-ssh'
        run: |-
          echo -e "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > /tmp/ssh_key
          chmod 0600 /tmp/ssh_key
          ssh -t -o StrictHostKeyChecking=accept-new -i /tmp/ssh_key ecco-deployer@api.coe-ecco.org \
            -- /bin/bash -i -s << "EOF"
            cd /var/projects/ecco && \
            echo $PWD && \
            git pull && ( echo "$( git rev-parse HEAD ) - $( date )" ) >> deploys.txt && \
            ./run_stack.sh prod && \
            exit $( docker container wait ecco-frontend-1 )
          EOF
          rm /tmp/ssh_key
  
      - id: 'test'
        run: |-
          echo '${{ steps.compute-ssh.outputs.stdout }}'
          echo '${{ steps.compute-ssh.outputs.stderr }}'
